### ISSUE TITLE
Ferramentas

### ISSUE THREAD

**Issue by AnHoff** [Requisitos-de-Software/2022.2-MEI#1]
# Descrição
Criar página no pages para falar sobre as ferramentas utilizadas no projeto.

# Tarefas
- [x] Criar página de ferramentas
- [x] Listar ferramentas utilizadas
- [x] Escrever sobre o uso de cada uma

# Critérios de aceitação
- [x] Listagem completa das ferramentas utilizadas

**Comment by VasconcelosJoao** [comment]
Pagina no GitHub pages sobre as ferramentas utilizadas no projeto, criada e revisada.
