### ISSUE TITLE
Pesquisa sobre Perfil de Usuário

### ISSUE THREAD

**Issue by AnHoff** [Requisitos-de-Software/2022.2-MEI#18]
# Descrição
Pesquisar sobre o tipo de usuário que utiliza o app e como ele o utiliza.

# Tarefas
- [x] Dados demográficos (idade, sexo, status socioeconômico);
- [x] Educação, profissão, experiência no cargo que ocupa, treinamento;
- [x] Experiência com computadores e com o site em questão ou semelhantes;
- [x] Tecnologia disponível;
- [x] Conhecimento do domínio, objetivos no sistema;
- [x] Tarefas do usuário que devem ser apoiadas pelo sistema;
- [x] Gravidade dos erros;
- [x] Motivação para o trabalho;
- [x] Idiomas e dialetos.

# Critérios de aceitação
- [x] Perfil de usuário completo traçado.

**Comment by PedroLSF** [comment]
Fiz uma análise de possíveis perfis e montei um por cima, acredito que esteja certo, me avisem se estiver faltando
[Perfil - MEI.pdf](https://github.com/Requisitos-de-Software/2022.2-MEI/files/10098504/Perfil.-.MEI.pdf)

**Comment by edudsan** [comment]
Aqui está o que eu fiz
[perfilMEI.pdf](https://github.com/Requisitos-de-Software/2022.2-MEI/files/10099142/perfilMEI.pdf)

**Comment by VasconcelosJoao** [comment]
Minha analise 
[PerfilMEI.pdf](https://github.com/Requisitos-de-Software/2022.2-MEI/files/10100076/PerfilMEI.pdf)
