### ISSUE TITLE
Técnicas de Elicitação

### ISSUE THREAD

**Issue by AnHoff** [Requisitos-de-Software/2022.2-MEI#20]
# Descrição
Escrever sobre técnicas de elicitação de requisitos e os motivos de certas técnicas terem sido escolhidas (ao menos 3 escolhidas e 5 apresentadas).

# Tarefas
- [ ] Escrever sobre as técnicas de elicitação estudadas em sala;
- [ ] Escolher 3, apontando os motivos para a escolha.

# Critérios de aceitação
- [ ] Documento com ao menos 5 técnicas descritas, revisadas e com bibliografia.

**Comment by Eruel6** [comment]
Documento criado e pronto para revisão na branche tecnicas-de-elicitacao
